# Generated by Django 4.2.8 on 2023-12-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_alter_category_userid_alter_expense_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total',
        ),
    ]
